export const Strings = {
  movies: 'Movies',
  community: 'Community',
  trailers: 'Trailers',
  home: 'Home',
  tvShows: 'TV Shows',
  internetConnectionCheck: 'Please check your internet connection',
  whatsPopular: "What's popular",
  freeToWatch: 'Free To Watch',
  latestTrailers: 'Latest Trailers',
  Trending: 'Trending',
  subTitle: 'watch Latest Trailer',
  streaming: 'Streaming',
  onTv: 'On Tv',
  forRent: 'For Rent',
  inTheaters: 'In Theaters',
  tv: 'Tv',
  today: 'Today',
  thisWeek: 'This Week',
  trailerStreaming: 'trailerStreaming',
  trailerOnTv: 'trailerOnTv',
  trailerForRent: 'trailerforRent',
  trailerInTheaters: 'trailerIntheater',
  playTrailer: 'Play Trailer',
};
